# Generated by Django 4.2.11 on 2024-04-02 13:41

import connect.models
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Task",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("task_name", models.CharField(max_length=100)),
                ("description", models.TextField()),
                ("request_covolunteer", models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name="Volunteering",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "date_of_volunteering",
                    models.DateField(
                        validators=[connect.models.validate_wednesday_date]
                    ),
                ),
                ("confirmed", models.BooleanField(default=False)),
                ("comments", models.TextField(blank=True, max_length=500)),
                (
                    "task",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="task_volunteering",
                        to="connect.task",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="user_volunteering",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
