# Generated by Django 4.2.11 on 2024-04-12 10:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('connect', '0003_rename_userprofile_profile'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='profile_picture',
        ),
    ]
