# Generated by Django 4.2.11 on 2024-04-12 14:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('connect', '0004_remove_profile_profile_picture'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='task',
            name='request_covolunteer',
        ),
        migrations.AddField(
            model_name='volunteering',
            name='request_covolunteer',
            field=models.BooleanField(default=False),
        ),
    ]
